### ISSUE TITLE
vfs_fat_spiflash: f_mount failed (13) with latest esp-idf

### ISSUE THREAD

**Issue by bastianhjaeger** [magicmicros/mk_espfat#1]
I am building a filesystem image with your script and upload it as described. 
My application runs with esp-idf and fails mounting the fat partition.

![Screenshot from 2020-06-16 22-10-35](https://user-images.githubusercontent.com/26868917/84823261-5a607600-b01e-11ea-96b2-0d58c9cc61dd.png)

Any suggestions what might be wrong?

I downloaded a workin FAT partition and compared the hexdump. Left is the working one from a new formatted FAT and right is the hexdump from your script.
![Uploading Screenshot from 2020-06-16 22-12-07.png…]()

[filesystem.zip](https://github.com/magicmicros/mk_espfat/files/4788879/filesystem.zip)

**Comment by magicmicros** [comment]
Looks like you missed the hexdump screenshot.
Your filesystem.img mounts fine on my Mac here, so the filesystem itself seems to be ok.
Note the addresses for where to load back the filesystem. You have to skip 0x1000 from the offset in the ESP partition. So if your partitions starts at 0x400000, you should program the filesystem image at 0x401000

**Comment by bastianhjaeger** [comment]
I oversaw this 0x1000 offset. Thanks. 

Work fine. Even with encryption enabled by running:
`esptool.py -p /dev/ttyUSB0 write_flash 0x401000 filesystem.img --encrypt`
